### PR TITLE
Add Euclidean type class

### PR DESCRIPTION
**Pull request by Bodigrim**
As discussed in https://github.com/cartazio/arithmoi/issues/166

I have prepared tests and laws for `quickcheck-classes` as well:
https://github.com/Bodigrim/quickcheck-classes/commits/master
https://github.com/Bodigrim/semirings/commits/master

### CODE REVIEW

**Comment by Bodigrim** [comment]
I wonder if it is acceptable to bake in `Eq a` as a superclass of `GcdDomain`:
```haskell
class (Eq a, Semiring a) => GcdDomain a where ...
```

**Comment by chessai** [comment]
instead of `Eq` being a top-level superclass of `GcdDomain`, why not just put that constraint into the default signatures?

**Comment by chessai** [comment]
aside from the Eq thing, this looks completely fine to me. as long as it builds with GHC >= 7.4. I'll test for that once the `Eq` thing is sorted out.

**Comment by Bodigrim** [comment]
Done. I've added Travis build to facilitate compatibility testing, if you do not mind.

**Comment by chessai** [comment]
I don't mind, I've always had trouble keeping up with travis though. I usually end up nuking it. However, https://github.com/haskell-CI/haskell-ci seems useful, and easy enough to keep up with.

**Comment by chessai** [comment]
How did you generate that travis script?

**Comment by Bodigrim** [comment]
I copy-pasted the travis script from another project of mine and replaced package name. I believe its distant ancestor was once generated by `haskell-ci`.

**Comment by chessai** [comment]
Okay, LGTM

**Comment by chessai** [comment]
Thank you!

**Pull request merged**
