### PR TITLE
Remove bad instances, remove Signum data type

### PR DESCRIPTION
**Pull request by kozross**
This addresses @Bodigrim's comments on #72.

### CODE REVIEW

**Comment by chessai** [comment]
restarted CI, failed due to windows linker error, which i expect to be transient

**Comment by chessai** [comment]
> restarted CI, failed due to windows linker error, which i expect to be transient

I was wrong. Will have to debug CI later. Possibly just needs an update to the GHCs.

**Comment by kozross** [comment]
We're still on an old (and no longer supported) version of Haskell Github Actions. That may have a lot to do with it.

**Comment by chessai** [comment]
> We're still on an old (and no longer supported) version of Haskell Github Actions. That may have a lot to do with it.

Thanks. Can you please rebase on top of master?

**Comment by kozross** [comment]
@chessai Done.

**Comment by hseg** [comment]
Sorry I'm joining in so late. Reviewed the `OrderedRing` patches, some remarks:
* Disagree with Bodigrim's assessment that complex integer rings are relevant here -- what order do they have?
* No need to require total order, it seems a [partially ordered ring](https://en.wikipedia.org/wiki/Partially_ordered_ring) suffices for this patch. Which incidentally rehabilitates the `Signum` type -- a po-ring is equivalently given by either:
  * an order satisfying
    * `x<y => x+z<y+z`
    * `0<x, 0<y => 0<xy`
  * a subset `P` called the _positive cone_ satisfying
    * `0∈P`
    * `P∩P={0}`
    * `P+P⊆P`
    * `PP⊆P`

  so `Positive` could just refer to elements of the positive cone
* The `IntN` `OrderedRing` instances are incoherent with them being given `Modular Ring` instances. One alternative is to provide both `Modular` and `Segment` wrappers, with the latter having the semantics of "an smaller-range approximation to a larger, lawful instance".
* The tuple instances can be restored, but note that they are noncanonical -- they depend on a choice of semigroup on `Signum`
* `abs` has an invalid law: `x-|x|≠0` for `x` negative. Instead you might want: `abs (x*y) == abs x * abs y`, `abs (x+y) <= abs x + abs y`
* `signum` laws can be abbreviated: `signum zero = zero`, `signum` is order-preserving
* If restoring the old API, take care when writing the `MINIMAL` pragma -- old defaults had definition dependencies `abs <- signum <- abs; signum' <- abs`, so the `MINIMAL` pragma was invalid
* `Down` cannot be given a valid `OrderedRing` instance, since `0 < 1` is a theorem of ordered rings and presumably the implied ordering for `Down` is the reverse of the standard ordering
* Might want a little TH/DerivingVia for the based on `Num` instances

**Comment by kozross** [comment]
@hseg - thanks for the feedback! It's very interesting and definitely raises good points. I do have some questions though:

* po-rings are a very general structure; in fact, _any_ `Ring` can be a po-ring trivially as long as it's an instance of `Eq` as well. How would the definitions you propose work in such a case?
* Partial orders are a notion which `base` doesn't contain. I'm not sure how big of a problem this is, but it's definitely food for thought.

**Comment by hseg** [comment]
Fair, missed that point re `Ord`.  It appears that any semiring is ordered (take positive cone `{0}`), but only some are so nontrivially.
I guess you could keep the `Ord` context, restricting the class to totally ordered rings.
To encode this in positive cone terminology, you'd want the axiom `not . all ((==Negative).signum) $ [x-y,y-x]`.
(If you could ensure `x-y/=0`, this is equivalently ``Positive `elem` map signum [x-y,y-x]``)

On 5 September 2021 3:12:02 am GMT+03:00, Koz Ross ***@***.***> wrote:
***@***.*** - thanks for the feedback! It's very interesting and definitely raises good points. I do have some questions though:

**Comment by hseg** [comment]
Fair, missed that point re `Ord`.  It appears that any semiring is ordered (take positive cone `{0}`), but only some are so nontrivially.
I guess you could keep the `Ord` context, restricting the class to totally ordered rings.
To encode this in positive cone terminology, you'd want the axiom `not . all ((==Negative).signum) $ [x-y,y-x]`.
(If you could ensure `x-y/=0`, this is equivalently ``Positive `elem` map signum [x-y,y-x]``)

**Pull request merged**
