### PR TITLE
Replace CPP instance derivation code

### LINKED ISSUE #63: Replace CPP instance derivation code with TH/DerivingVia
CPP instances as written are less flexible (eg to implement #62 we'd need differing derived instances for the types that are morally integers and those that are morally fields).

Besides, it's ugly, and we have principled alternatives in terms of TH (if we want backwards compatibility) or DerivingVia (supports ghc >=8.6 only, which is two years old).

Am willing to implement this if agreeable.

### PR DESCRIPTION
**Pull request by hseg**
Closes #63

### CODE REVIEW

**Comment by Bodigrim** [comment]
Thanks! 
I'm certainly all for switching to DerivingVia for newer GHCs. On the other hand, I do not want to depend on TemplateHaskell, but it might be acceptable if limited to old GHCs only. (Maybe we could retain CPP for old GHCs?..)

**Comment by hseg** [comment]
I prefer TH for readability+gotcha avoidance, but it's your call.

On August 14, 2020 5:54:34 PM GMT+03:00, Bodigrim <notifications@github.com> wrote:
>Thanks! 
>I'm certainly all for switching to DerivingVia for newer GHCs. On the
>other hand, I do not want to depend on TemplateHaskell, but it might be
>acceptable if limited to old GHCs only. (Maybe we could retain CPP for
>old GHCs?..)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/chessai/semirings/pull/64#issuecomment-674113675

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Bodigrim** [comment]
@chessai what do you think about it?

**Comment by chessai** [comment]
+1 to DerivingVia for newer GHCs,
+.5 to TH for older GHCs. It is more readable. Plus I plan on dropping support for 7.x soon which makes the window pretty small.
Hopefully after a while we can eventually drop support for pre-8.6 altogether. But it's much too soon right now.

I think this PR is fine. If you don't have any serious objections @Bodigrim i think this can be merged (after the merge conflicts are resolved)

**Comment by Bodigrim** [comment]
LGTM. @hseg please resolve conflicts.

**Comment by hseg** [comment]
Missed the new commits on master. Sure, give me a moment.
Sorry for being out of touch, will try to clean both this and #65 up tonight.

**Comment by Bodigrim** [comment]
@hseg thanks, merged!

**Pull request merged**
