### PR TITLE
Test for non-terminating GenericSemiring instances

### PR DESCRIPTION
**Pull request by reactormonk**
The test now hangs, something's not right here.

### CODE REVIEW

**Comment by chessai** [comment]
Do you mean, the code in this PR hangs? Or that something else already present hangs? 

The fact that it's hanging is almost certainly a GHC bug. I wouldn't doubt it, since I've found a few bugs with DerivingVia just myself, most of which resulted in panics.

**Comment by reactormonk** [comment]
Yeah, the code hangs on my local machine via `stack test`. It's a replication from a bug which I encountered using it via `DerivingVia`. Seems to pass just fine on CI though...

**Comment by chessai** [comment]
Passes CI?? That's strange to me. I will try locally today

**Comment by chessai** [comment]
CI isn't running the tests. Locally:

```
> AB (A 3) (B 4) + AB (A 4) (B 3)
```

hangs

**Comment by chessai** [comment]
crap; i know what the error is.

**Comment by chessai** [comment]
Ok, there were two problems:

1. Infinite loop in the instance for GenericSemiring (used its own Generic instance instead of the underlying type's) and
2. gtimes was implemented improperly for product types!

These are fixed now.

Sorry for the screwup, I've never actually used the Generics code before!

**Comment by chessai** [comment]
strange, i didn't close this, and also was able to force push to your branch? ugh. i'll make a separate PR. apologies.

**Pull request closed without merging**
