### PR TITLE
drop 8.0 support and re-enable haddocks in ci

### PR DESCRIPTION
**Pull request by chessai**

### CODE REVIEW

**Comment by chessai** [comment]
@kozross now even 8.4 haddocks is failing, where before it wasn't. strange.

**Comment by Bodigrim** [comment]
I think it is overzealous to annotate every instance with `@since 0.7` when a type itself has `@since 0.7`.

**Comment by andreasabel** [comment]
I don't think such a basic library should drop support for GHC versions without strong need.  What makes it hard to support GHC 8.0?

The context: I am considering on depend on this package for Agda, which supports GHC 8.0:
- https://github.com/agda/agda/issues/5863

**Comment by chessai** [comment]
I think @andreasabel has a good point that we shouldn't drop support for 8.0.x/8.2.x, but rather disable haddock in CI for 8.0.x and 8.2.x

**Pull request closed without merging**
